BarnameNevis1401/Models/SetTagsViewModel.cs
namespace BarnameNevis1401.Models;

public class SetTagsViewModel
{
    public string[] Tags { get; set; }
    public int Id { get; set; }
}

BarnameNevis1401/Controllers/ImageController.cs
using System.Security.Claims;
using BarnameNevis1401.Core;
using BarnameNevis1401.Data;
using BarnameNevis1401.Data.SqlServer;
using BarnameNevis1401.Domains.Images;
using BarnameNevis1401.Infrastructure;
using BarnameNevis1401.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BarnameNevis1401.Controllers;

[Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
public class ImageController : Controller
{
    private IWebHostEnvironment _env;
    private ApplicationDbContext _context;
    private IImageService _imageService;
    private ITagService _tagService;
    private IUnitOfWork _uow;
    public ImageController(IWebHostEnvironment env, ApplicationDbContext context, IImageService imageService, ITagService tagService, IUnitOfWork uow)
    {
        _env = env;
        _context = context;
        _imageService = imageService;
        _tagService = tagService;
        _uow = uow;
    }

    // GET
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Index(ImageUploadModel model)
    {
        
        if (ModelState.IsValid)
        {
            var isValid = new Utils().IsValidImage(model.Picture.FileName);
            if (!isValid)
            {
                ModelState.AddModelError("Picture","فرمت تصویر معتبر نمیباشد");
                return View(model);
            }
            var path = Path.Combine(_env.ContentRootPath, "Pictures");
            var imageName = new Utils().SaveFile(model.Picture, path);

            var userId = HttpContext.User.GetUserId();

            byte[] image = null;
            using (var ms=new MemoryStream())
            {
                model.Picture.CopyTo(ms);
                image = ms.ToArray();
            }
            var imageItem = new ImageItem()
            {
                FileName = imageName,
                FileSize = model.Picture.Length,
                Type = model.Picture.ContentType,
                UserId = userId,
                Image = image,
                Names = new []{"canon","fp2","light"},
                UploadTimeDuration = TimeSpan.FromSeconds(5)
            };
            _context.ImageItems.Add(imageItem);
            var rows = _context.SaveChanges();
            if (rows == 0)
            {
                ModelState.AddModelError("Picture","خطا در ذخیره تصویر");
                return View(model);
            }
            return RedirectToAction("Index");

        }

        return View(model);
    }

    public IActionResult ShowImage(int id)
    {
        var imageItem = _context.ImageItems.FirstOrDefault(x => x.Id == id);
        if (imageItem == null)
            return NotFound();

        var path = Path.Combine(_env.ContentRootPath, "Pictures", imageItem.FileName);
        return File(new FileStream(path, FileMode.Open), imageItem.Type);
    }

    public IActionResult List(int id=1)
    {
        var pageSize = 12;
        var skip = (id - 1) * pageSize;
        
        var images = _context.ImageItems
            .OrderByDescending(x=>x.Id)
            .Skip(skip)
            .Take(pageSize)
            .ToList();
        
        return View(images);
    }

    [HttpGet]
    public async Task<IActionResult> SetTags(int id)
    {
        var image = await _imageService.GetImage(id);
        if (image == null)
            return NotFound();

        var tags = await _imageService.GetTagsAsync(id);

        var vm = new SetTagsViewModelGet()
        {
            ImageItem = image,
            Tags = tags
        };
        return View(vm);
    }

    [HttpPost]
    public async Task<IActionResult> SetTags(SetTagsViewModel viewModel)
    {
        var tags = await _imageService.GetTagsAsync(viewModel.Id);

        foreach (var tag in viewModel.Tags)
        {
            // 1-Tag ID
            var tagId = 0;
            var parsable = int.TryParse(tag, out tagId);
            if (!parsable)
            {
                tagId = await _tagService.SearchTagAsync(tag);
            }
            
            //2-Already Registered?

            Tag dbTag = null;
            if (tagId > 0)
            {
                var isRegistered = tags.Any(x => x.Id == tagId);
                if(isRegistered)
                    continue;

                dbTag = await _tagService.FindTagAsync(tagId);

            }
            else
            {
                dbTag = new Tag()
                {
                    Name = tag,
                    UserId = User.GetUserId(),
                };
                await _tagService.AddTagAsync(dbTag);
            }

            await _imageService.NewImageTagAsync(new ImageTag()
            {
                Tag = dbTag,
                ImageItemId = viewModel.Id
            });
        }

        foreach (var dbtag in tags)  
        {
            if (viewModel.Tags.Contains(dbtag.Id.ToString()) || viewModel.Tags.Contains(dbtag.Name))
            {
                continue;
            }

            dbtag.IsRemoved = true;
        }
        var rows = await _uow.SaveChangesAsync();

        return Json(new { result = rows > 0 });
    }

    [AllowAnonymous]
    public async Task<IActionResult> GetTagsFromSP(string id)
    {
        var tags = await _tagService.FindTageByName(id);
        return Json(tags);
    }
}

BarnameNevis1401/Controllers/TagController.cs
using BarnameNevis1401.Core;
using BarnameNevis1401.Data.SqlServer;
using BarnameNevis1401.DataTable;
using BarnameNevis1401.Domains.Images;
using BarnameNevis1401.Infrastructure;
using BarnameNevis1401.Models;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;

namespace BarnameNevis1401.Controllers;

public class TagController : Controller
{
    private ITagService _tagService;
    private IWebHostEnvironment _env;

    private ApplicationDbContext _context;
    // GET
    public TagController(ITagService tagService, ApplicationDbContext context, IWebHostEnvironment env)
    {
        _tagService = tagService;
        _context = context;
        _env = env;
    }

    public IActionResult Index()
    {
        return View();
    }

    public async Task<IActionResult> LoadTags(DataTableParam param)
    {
        var s = Request.Query["search[value]"].ToString();
        var tags = await _tagService.GetTags(User.GetUserId(),param.Start, param.Length,s);
        var total = await _tagService.GetTagsCount(User.GetUserId());
        var filter = await _tagService.GetTagsCount(User.GetUserId(),s);
        var result = new DataTableResult<TagData>();
        result.Data = tags;
        result.RecordsTotal = total;
        result.RecordsFiltered = filter;
        result.Draw = param.draw;
        return Json(result);
    }

    [HttpPost]
    public async Task<IActionResult> RemoveTag(int id)
    {
        await _tagService.Remove(id);
        var rows = await _context.SaveChangesAsync();

        return Json(new { result = rows > 0 });
    }
    
    [HttpPost]
    public async Task<IActionResult> RemoveSoftTag(int id)
    {
        var tag =await _tagService.FindTagAsync(id);
        tag.IsRemoved = true;
        var rows = await _context.SaveChangesAsync();

        return Json(new { result = rows > 0 });
    }

    public IActionResult ReadTags()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> ReadTags(IFormFile file)
    {
        var utils = new Utils();
        var path = Path.Combine(_env.ContentRootPath, "Excels");
        var fileName=utils.SaveFile(file,path);

        var fullPath = Path.Combine(path, fileName);
        using (ExcelPackage package=new ExcelPackage(new FileInfo(fullPath)))
        {
            var sheet = package.Workbook.Worksheets.First();
            var rowStart = sheet.Dimension.Start.Row;
            var rowEnd = sheet.Dimension.End.Row;

            var colStart =sheet.Dimension.Start.Column;
            var colEnd = sheet.Dimension.Start.Column;

            var tags = new List<string>();
            for (int i = rowStart;  i<= rowEnd; i++)
            {
                var tag = sheet.Cells[i, 1].Value.ToString();
                tags.Add(tag);
            }

            var newTags = tags
                .Select(x => new Tag()
                {
                    Name = x,
                    UserId = User.GetUserId()
                })
                .ToList();

            await _tagService.AddTagsAsync(newTags);
            var rows = await _context.SaveChangesAsync();
            if (rows > 0)
                return Content("OK");
            return Content("NOK");
        }
    }
    [HttpGet]
    public async Task<IActionResult> Add()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Add(AddTagViewModel model)
    {
        if (ModelState.IsValid)
        {
            var tagIsExited = await _tagService.FindTagAsync(model.TagName);
            if (tagIsExited == null)
            {
                var tag = new Tag()
                {
                    Name = model.TagName,
                    UserId = User.GetUserId()
                };
                var rows = await _tagService.AddTagAsync(tag);
                if (rows > 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("Not Ok!");
                }
            }
            else
            {
                ModelState.AddModelError("TagName","این تگ قبلا ثبت شده است");
                return View(model);
            }
        }
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var tag = await _tagService.FindTagAsync(id);
        return View(tag);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Tag tag)
    {
        var rows = await _tagService.EditTagAsync(tag);
        if (rows > 0)
        {
            return RedirectToAction("Index");
        }
        else
        {
            return Content("Not Ok");
        }
    }

    public async Task<IActionResult> GetTags(string query)
    {
        var tags=await _tagService.FilterTags(User.GetUserId(), query);
        var output = tags
            .Select(x => new
            {
                x.Id,
                x.Name
            })
            .ToList();

        return Json(output);
    }
}

BarnameNevis1401/Views/Image/Index.cshtml
@model ImageUploadModel
<form method="post" enctype="multipart/form-data" asp-controller="Image" asp-action="Index">
    <input type="file" asp-for="Picture"/>
    <span asp-validation-for="Picture"></span>
    <button type="submit" class="btn btn-primary">Upload</button>
</form>

BarnameNevis1401/Views/Image/List.cshtml
@using BarnameNevis1401.Infrastructure
@model List<BarnameNevis1401.Domains.Images.ImageItem>

<div class="container">
    <div class="row">
        @{
            if (Model.Count == 0)
            {
                <h1>Not Found</h1>
            }
            foreach (var imageItem in Model)
            {
                <div class="col-3">
                    <img class="img-fluid" src="@Url.Action("ShowImage","Image",new {id=imageItem.Id})"/>
                    <span class="badge badge-info">@imageItem.FileName : @imageItem.FileSize.ToUnit()</span>
                </div>
            }
        }
    </div>
</div>

BarnameNevis1401/Views/Image/SetTags.cshtml
@model SetTagsViewModelGet

<form method="post" >
    <img src="@Url.Action("ShowImage",new {id=Model.ImageItem.Id})" style="width: 400px;" class="img-fluid" />
    
    <br/>
    
    <div class="tags-input" id="_my_tags_input">
        <span class="data">
               @{
                    foreach (var tag in Model.Tags)
                    {
                        <span class="tag"><span class="text" _value="@tag.Id">@tag.Name</span><span class="close">×</span></span>
                    }
                }
                            
        </span>
        <span class="autocomplete"><input type="text"><div class="autocomplete-items">
             
            </div>
           </span>
    </div>
    
    
    <br/>
    <button id="btn"  type="submit" class="btn btn-primary">Save Tags</button>
</form>

@section Header
{
    <link href="~/dist/tagsinput/tags.css" rel="stylesheet" />
}

@section Scripts
{
    <script src="~/dist/tagsinput/tags.js"></script>
    <script>
  function runSuggestions(query) {
   
      /*
      using ajax to populate suggestions
       */
      let sug_area=$('.autocomplete .autocomplete-items');
      $.getJSON("@Url.Action("GetTags", "Tag")?query=" + query, function( data ) {
          //update the data used for suggestions for purpose of retrieval after suggestions click
          _tag_input_suggestions_data = data;
          $.each(data,function (key,value) {
              let template = $("<div>"+value.name+"</div>").hide()
              sug_area.append(template)
              template.show()
   
          })
      });
   
  }
  $('#_my_tags_input').find("input").on('keyup',function(e){
      runSuggestions($(this).val());
  });
  var submit=false;
  $("form").submit(function (e){
      if (submit==false)
      {
                e.preventDefault();
                return;
      }
      submit=false;
      })
      
      $("#btn").on('click',function (){
            let tags = $('#_my_tags_input').tagsValues();
            console.log(tags);
            
            $.ajax({
            url:'@Url.Action("SetTags")',
            data:{
                tags,
                id:@Model.ImageItem.Id
                },
            type:'POST',
            success:function (data){
                if (data.result===true)
                    {
                        alert('Saved');
                        return;
                     }
                alert('NotSaved');
                }
            });
           // submit=true;
            //$("form").submit();
      });
  </script>
}