BarnameNevis1401/Controllers/AuthController.cs
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using BarnameNevis1401.ApplicationService;
using BarnameNevis1401.Core;
using BarnameNevis1401.Data;
using BarnameNevis1401.Data.SqlServer;
using BarnameNevis1401.Domains.Users;
using BarnameNevis1401.Email;
using BarnameNevis1401.Infrastructure;
using BarnameNevis1401.Models;
using BarnameNevis1401.SmsManagers;
using DNTCaptcha.Core;
using Ghasedak.Core;
using Hangfire;
using MailKit.Net.Smtp;
using MailKit.Security;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MimeKit;
using MimeKit.Text;
using MimeMessage = MimeKit.MimeMessage;

namespace BarnameNevis1401.Controllers;

public class AuthController : Controller
{
   private ApplicationDbContext _context;
   private readonly IWebHostEnvironment _env;
   private IUserService _userService;
   private EmailSettings _emailSettings;

   public AuthController(ApplicationDbContext context,IWebHostEnvironment _env, IUserService userService
      ,IOptionsSnapshot<EmailSettings> options)
   {
      _context = context;
      this._env = _env;
      _userService = userService;
      _emailSettings = options.Value;
   }

   public IActionResult Login(string returnUrl)
   {
      ViewData["ReturnUrl"] = returnUrl;
      ViewBag.ReturnUrl = returnUrl;
      return View();
   }

   [HttpPost]
   [ValidateDNTCaptcha(ErrorMessage = "لطفا کد امنیتی را وارد کنید",
      CaptchaGeneratorLanguage = Language.Persian,
      CaptchaGeneratorDisplayMode = DisplayMode.ShowDigits)]
   public async Task<IActionResult> Login(LoginModel model)
   {
      
      if (ModelState.IsValid)
      {
         var user = _userService.Login(model.Username, model.Password);
         if (user == null)
         {
            ModelState.AddModelError("Username","چنین گاربری یافت نشد");
            return View(model);
         }

         var s = "12";
         var x = s.ToInt();
         

         var claim = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
         claim.AddClaim(new Claim(ClaimTypes.NameIdentifier,user.Id.ToString()));
         claim.AddClaim(new Claim(ClaimTypes.GivenName,user.Username));
         claim.AddClaim(new Claim(ClaimTypes.Name,user.FullName));
         claim.AddClaim(new Claim(ClaimTypes.SerialNumber,user.SerialNumber));
         if(user.IsAdmin)
            claim.AddClaim(new Claim(ClaimTypes.Role,"Admin"));
         
         var claimPrincipals = new ClaimsPrincipal(claim);
         await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,claimPrincipals);
         if (String.IsNullOrEmpty(model.ReturnUrl) == false && model.ReturnUrl!="/")
            return Redirect(model.ReturnUrl);
         return RedirectToAction("Index", "Home");
      }
      return View(model);
   }

   public async Task<IActionResult> Logout()
   {
      await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
      return RedirectToAction("Login");
   }

   [HttpGet]
   public IActionResult Register()
   {
      return View();
   }

   [HttpPost]
   public async Task<IActionResult> Register(RegisterModel model)
   {
      if (ModelState.IsValid)
      {
         var isExists =await _userService.IsExists(model.Username,model.Email,model.MobileNumber);
         if (isExists != null)
         {
            if (isExists.UsernameExists)
            {
               ModelState.AddModelError("Username","نام کاربری تکراری است");
            }
            if (isExists.MobileExists)
            {
               ModelState.AddModelError("MobileNumber","شماره همراه  تکراری است");
            }
            if (isExists.EmailExists)
            {
               ModelState.AddModelError("Email","ایمیل  تکراری است");
            }
            
            if (isExists.IsExists)
            {
               return View(model);

            }
         }

        

         var newUser = new User()
         {
            FirstName = "",
            LastName = "",
            
            Username = model.Username,
            Password = model.Password.Hash(),
            Email = model.Email,
            Mobile = model.MobileNumber
         };
         newUser.GenerateSerialNumber();
         await _userService.NewUser(newUser);
         var otpCode = new OtpCode()
         {
            Code = Utils.RandomString(4,RandomType.OnlyNumbers),
            User = newUser
         };
         _userService.AddOtpCode(otpCode);
         var rows = _context.SaveChanges();
         if (rows > 0)
         {
            //send sms
            BackgroundJob.Enqueue(() => SendSms(model.MobileNumber, otpCode.Code));
            return RedirectToAction("Otp");
         }
         else
         {
            return View(model);
         }
      }
      return View(model);
   }

   public async Task SendSms(string mobile,string code)
   {
      var smsManager = SmsFactory.Get();
      await smsManager.SendSmsTemplate("Login1401", mobile, new[] { code });
   }
   public IActionResult Otp()
   {
      return View();
   }

   public IActionResult CheckEmailSettings()
   {
      return Content($"Server={_emailSettings.SmtpServer} - Username={_emailSettings.Username} -" +
                     $"Password={_emailSettings.Password} - Port={_emailSettings.Port}");
   }
   private bool RemoteServerCertificateValidationCallback(object sender, System.Security.Cryptography.X509Certificates.X509Certificate certificate, System.Security.Cryptography.X509Certificates.X509Chain chain, System.Net.Security.SslPolicyErrors sslPolicyErrors)
   {
      //Console.WriteLine(certificate);
      return true;
   }

   public async Task<IActionResult> ChangeSerialNumber()
   {
      var userId = User.GetUserId();
      var user = await _userService.FindUserAsync(userId);
      user.GenerateSerialNumber();
      var rows = await _context.SaveChangesAsync();
      return Content("Rows=" + rows);
   }

   [HttpPost]
   public IActionResult Otp(OtpModel model)
   {
      if (ModelState.IsValid)
      {
         var otp = _userService.GetOtpCode(model.Code);

         if (otp==null || !otp.IsValid)
         {
            ModelState.AddModelError("Code","کد مورد نظر معتبر نمیباشد");
            return View(model);
         }

         otp.IsUsed = true;
         otp.User.IsActive = true;

         var rows = _context.SaveChanges();
         if (rows > 0)
         {
      
            //============= Message ==================
            var message = new MimeMessage();
            message.From.Add(new MailboxAddress("آموزشگاه برنامه نویس",_emailSettings.Username));
            message.To.Add(new MailboxAddress(otp.User.LastName,otp.User.Email));
            message.Subject = "به مدیریت تصاویر خوش آمدید";
            
            var body = new TextPart(TextFormat.Html)
            {
               Text = "به برنامه <a href='https://barnameneviss.ir/'>برنامه نویس</a> خوش آمدید"
            };

            var multipartBody = new Multipart("mixed");
            multipartBody.Add(body);
            
            var stream = new FileStream(Path.Combine(_env.WebRootPath,"1.jpg"), FileMode.Open);
            var attachment = new MimePart ("image/jpg") {
               Content = new MimeContent (stream),
               ContentDisposition = new ContentDisposition (ContentDisposition.Attachment),
               ContentTransferEncoding = ContentEncoding.Base64,
               FileName = Path.GetFileName ("berry.jpg")
            };
            multipartBody.Add (attachment);
            message.Body = multipartBody;
            
            //===============================
            
            //send email
            System.Net.ServicePointManager.ServerCertificateValidationCallback = new System.Net.Security.RemoteCertificateValidationCallback(RemoteServerCertificateValidationCallback);
            var client = new SmtpClient();
            client.Connect(_emailSettings.SmtpServer,_emailSettings.Port,_emailSettings.SSL);
            client.Authenticate(_emailSettings.Username,_emailSettings.Password);
            client.Send(message);
            client.Disconnect(true);
            
            return RedirectToAction("Login");
         }
         else
         {
            ModelState.AddModelError("Code","خطا در ثبت اطلاعات");
            return View(model);
         }
      }
         
      return View();
   }
}

BarnameNevis1401/Controllers/TagController.cs
using BarnameNevis1401.Core;
using BarnameNevis1401.Data.SqlServer;
using BarnameNevis1401.DataTable;
using BarnameNevis1401.Domains.Images;
using BarnameNevis1401.Infrastructure;
using BarnameNevis1401.Models;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;

namespace BarnameNevis1401.Controllers;

public class TagController : Controller
{
    private ITagService _tagService;
    private IWebHostEnvironment _env;

    private ApplicationDbContext _context;
    // GET
    public TagController(ITagService tagService, ApplicationDbContext context, IWebHostEnvironment env)
    {
        _tagService = tagService;
        _context = context;
        _env = env;
    }

    public IActionResult Index()
    {
        return View();
    }

    public async Task<IActionResult> LoadTags(DataTableParam param)
    {
        var s = Request.Query["search[value]"].ToString();
        var tags = await _tagService.GetTags(User.GetUserId(),param.Start, param.Length,s);
        var total = await _tagService.GetTagsCount(User.GetUserId());
        var filter = await _tagService.GetTagsCount(User.GetUserId(),s);
        var result = new DataTableResult<TagData>();
        result.Data = tags;
        result.RecordsTotal = total;
        result.RecordsFiltered = filter;
        result.Draw = param.draw;
        return Json(result);
    }

    [HttpPost]
    public async Task<IActionResult> RemoveTag(int id)
    {
        await _tagService.Remove(id);
        var rows = await _context.SaveChangesAsync();

        return Json(new { result = rows > 0 });
    }
    
    [HttpPost]
    public async Task<IActionResult> RemoveSoftTag(int id)
    {
        var tag =await _tagService.FindTagAsync(id);
        tag.IsRemoved = true;
        var rows = await _context.SaveChangesAsync();

        return Json(new { result = rows > 0 });
    }

    public IActionResult ReadTags()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> ReadTags(IFormFile file)
    {
        var utils = new Utils();
        var path = Path.Combine(_env.ContentRootPath, "Excels");
        var fileName=utils.SaveFile(file,path);

        var fullPath = Path.Combine(path, fileName);
        using (ExcelPackage package=new ExcelPackage(new FileInfo(fullPath)))
        {
            var sheet = package.Workbook.Worksheets.First();
            var rowStart = sheet.Dimension.Start.Row;
            var rowEnd = sheet.Dimension.End.Row;

            var colStart =sheet.Dimension.Start.Column;
            var colEnd = sheet.Dimension.Start.Column;

            var tags = new List<string>();
            for (int i = rowStart;  i<= rowEnd; i++)
            {
                var tag = sheet.Cells[i, 1].Value.ToString();
                tags.Add(tag);
            }

            var newTags = tags
                .Select(x => new Tag()
                {
                    Name = x,
                    UserId = User.GetUserId()
                })
                .ToList();

            await _tagService.AddTagsAsync(newTags);
            var rows = await _context.SaveChangesAsync();
            if (rows > 0)
                return Content("OK");
            return Content("NOK");
        }
    }
    [HttpGet]
    public async Task<IActionResult> Add()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Add(AddTagViewModel model)
    {
        if (ModelState.IsValid)
        {
            var tagIsExited = await _tagService.FindTagAsync(model.TagName);
            if (tagIsExited == null)
            {
                var tag = new Tag()
                {
                    Name = model.TagName,
                    UserId = User.GetUserId()
                };
                var rows = await _tagService.AddTagAsync(tag);
                if (rows > 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("Not Ok!");
                }
            }
            else
            {
                ModelState.AddModelError("TagName","این تگ قبلا ثبت شده است");
                return View(model);
            }
        }
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var tag = await _tagService.FindTagAsync(id);
        return View(tag);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Tag tag)
    {
        var rows = await _tagService.EditTagAsync(tag);
        if (rows > 0)
        {
            return RedirectToAction("Index");
        }
        else
        {
            return Content("Not Ok");
        }
    }

    public async Task<IActionResult> GetTags(string query)
    {
        var tags=await _tagService.FilterTags(User.GetUserId(), query);
        var output = tags
            .Select(x => new
            {
                x.Id,
                x.Name
            })
            .ToList();

        return Json(output);
    }
}

BarnameNevis1401/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/fontawesome.css">
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/solid.css">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      @RenderBody()
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="~/plugins/jquery/jquery.min.js"></script>
<script src="~/lib/unobtrusive-ajax.js"></script>
<!-- Bootstrap 4 -->
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>
</html>

BarnameNevis1401/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Dashboard</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="~/plugins/fontawesome-free/css/fontawesome.css">
  <link rel="stylesheet" href="~/plugins/fontawesome-free/css/solid.css">

  
 
  <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  
  <!-- Bootstrap 4 RTL -->
  <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
  <!-- Custom style for RTL -->
  <link rel="stylesheet" href="~/dist/css/custom.css">
  
  @await RenderSectionAsync("Header",false)
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
        @await Html.PartialAsync("_NavBar")
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @{
    if (User.IsInRole("Admin"))
    {
      Html.RenderPartial("_adminSideBar");

    }
    else
    {
      Html.RenderPartial("_SideBar");
    }
            }
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

 
    <!-- Main content -->
    <section class="content">
      @RenderBody()
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.0-rc.1
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="~/plugins/jquery/jquery.min.js"></script>

<!-- Bootstrap 4 rtl -->
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>


<!-- overlayScrollbars -->
<script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="~/dist/js/adminlte.js"></script>
@await  RenderSectionAsync("Scripts",false)
</body>
</html>

BarnameNevis1401/Views/Shared/_NavBar.cshtml
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav mr-auto-navbav">
      <!-- Messages Dropdown Menu -->
      @await Component.InvokeAsync("SpaceReportComponent",new {defaultPercent=70})
      <!-- Notifications Dropdown Menu -->
      
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>

BarnameNevis1401/Views/Shared/_SideBar.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Mvc.TagHelpers
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">@{
                                        var u = User.Claims.First(x => x.Type == ClaimTypes.Name).Value;
                                        @u
                                      }</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-image"></i>
              <p>
                مدیریت تصاویر
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a asp-controller="Image" asp-action="Index" class="nav-link">
                  <i class="far fa-upload nav-icon"></i>
                  <p>آپلود تصاویر</p>
                </a>
              </li>
              <li class="nav-item">
                <a asp-controller="Image" asp-action="List" class="nav-link">
                  <i class="far fa-list nav-icon"></i>
                  <p>لیست تصاویر</p>
                </a>
              </li>
              
            </ul>
          </li>
 
          
          
          <li class="nav-item has-treeview ">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tag"></i>
              <p>
                مدیریت برچسب ها
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a asp-controller="Tag" asp-action="Add" class="nav-link">
                  <i class="far fa-pen nav-icon"></i>
                  <p> تعریف برچسب</p>
                </a>
              </li>
              <li class="nav-item">
                <a asp-controller="Tag" asp-action="Index" class="nav-link">
                  <i class="far fa-list nav-icon"></i>
                  <p> لیست برچسب ها</p>
                </a>
              </li>
                        
            </ul>
            
          </li>
          
          
          <li class="nav-item has-treeview ">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-floppy-disk"></i>
              <p>
                مدیریت فضای دیسک
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item @(Context.Request.Path.Value=="/ok"?"active":"")">
                <a href="./index.html" class="nav-link">
                  <i class="far fa-compact-disc nav-icon"></i>
                  <p> فضای دیسک</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="./index2.html" class="nav-link">
                  <i class="far fa-money-bill nav-icon"></i>
                  <p> پرداخت ها</p>
                </a>
              </li>
                        
            </ul>
            
          </li>
          
          
          <li class="nav-item">
            <a class="nav-link logout" asp-action="Logout" asp-controller="Auth">
              <i class="fas fa-right-from-bracket"></i>
              خروج از حساب کاربری
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

BarnameNevis1401/Views/Shared/_adminSideBar.cshtml
@using System.Security.Claims

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">@{
                                        var u = User.Claims.First(x => x.Type == ClaimTypes.Name).Value;
                                        @u
                                      }</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
         
          
          <li class="nav-item has-treeview ">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-floppy-disk"></i>
              <p>
                مدیریت فضای دیسک
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item @(Context.Request.Path.Value=="/ok"?"active":"")">
                <a href="./index.html" class="nav-link">
                  <i class="far fa-compact-disc nav-icon"></i>
                  <p> فضای دیسک</p>
                </a>
              </li>
              <li class="nav-item">
                <a asp-controller="Payment" asp-action="ExportExcel" class="nav-link">
                  <i class="far fa-money-bill nav-icon"></i>
                  <p> پرداخت ها</p>
                </a>
              </li>
                        
            </ul>
            
          </li>
          
                
                    
          <li class="nav-item">
            <a class="nav-link logout" asp-action="Logout" asp-controller="Auth">
              <i class="fas fa-right-from-bracket"></i>
              خروج از حساب کاربری
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>